name: test deterministic operation

on: [push, pull_request]


jobs:
  build:
    name: Runs the deterministic operation test
    runs-on: ubuntu-20.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install packages
      run: sudo apt install build-essential nettle-dev libxxhash-dev time disorderfs
    - name: bootstrap
      run: ./bootstrap.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: run determinism test
      run: testcases/verify_deterministic_operation.sh
    - name: store logs as artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
         path: '**/*.log'

