name: build variants

on: [push, pull_request]


jobs:
  build:
    name: Runs the quality script
    runs-on: ubuntu-22.04

    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: install packages
      run: sudo apt install build-essential nettle-dev libxxhash-dev time libc6-i386 gcc-multilib g++-multilib valgrind libc++-dev libc++abi-dev clang
    - name: run do_quality_checks.sh
      run: ./do_quality_checks.sh
    - name: store logs as artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
         path: '**/*.log'

